name: CPP-COSO - CLANG-TIDY

on:
  pull_request:
    branches: [ main ]
env:
  BUILD_TYPE: Debug
  BOOST_VERSION: 1.78.0

permissions: write-all

jobs:
 clang-tidy-analyze:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Install boost
      uses: MarkusJx/install-boost@v2.0.0
      id: install-boost
      with:
        boost_version: ${{env.BOOST_VERSION}}

    - name: Generate Target
      run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/bin -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_CXX_USE_RESPONSE_FILE_FOR_INCLUDES=OFF -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang  -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      env:
        BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}

    - name: Build Tools
      run: cmake --build ${{github.workspace}}/bin
   
    - name: Run clang-tidy
      uses: ZedThree/clang-tidy-review@v0.7.0
      id: review
      with:
         build_dir: bin

 
